
import arvoregenealogica.arvore.ArvoreGenealogica;
import arvoregenealogica.arvore.Nodo;
import arvoregenealogica.grafos.Grafos;
import arvoregenealogica.listafilhos.NodoLista;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Period;
import java.time.ZoneOffset;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FLAVIO
 */
public class ArvoreFormUI extends javax.swing.JFrame {
    
    Grafos grafo;
    String path = null;
    ArvoreGenealogica arvore = new ArvoreGenealogica();
    SimpleDateFormat data_nasc = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form ArvoreFormUI
     * @param arvore
     */
    
    //Setters
    private void SetArvore(ArvoreGenealogica arvore){
        this.arvore = arvore;
    }
    
    private void SetPath(String path){
        this.path = path;
    }
    
    private void SetGrafo(Grafos grafo){
        this.grafo = grafo;
    }
    //Getters
    private ArvoreGenealogica GetArvore(){
        return this.arvore;
    }
    
    private Grafos GetGrafo(){
        return this.grafo;
    }
    
    private String GetPath(){
        return this.path;
    }
    
    private void CarregarArquivo(){
        try{
            if(GetPath() != null){
                ArrayList<String> lista_string = new ArrayList();
                BufferedReader br = new BufferedReader(new FileReader(GetPath()));
                while(br.ready()){
                String linha = br.readLine();
                String string = new String();
                for(int cont = 0; cont < linha.length(); cont++){
                    char letra = linha.charAt(cont);
                    if(';' == letra){
                        lista_string.add(string);
                        string = new String();
                        try{
                            GetArvore().InserirNodo(lista_string.get(0), lista_string.get(1), lista_string.get(2), lista_string.get(3), lista_string.get(4), data_nasc.parse(lista_string.get(5)), null);
                        } catch (ParseException ex) {
                            Logger.getLogger(ArvoreFormUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        lista_string = new ArrayList();
                    }
                    if(',' != letra){
                        string +=letra;
                    }else{
                        lista_string.add(string);
                        string = new String();
                    }
                }
                }br.close();
            }
        }catch(IOException ioe){
            ioe.printStackTrace();
        }
    }
    
    public ArvoreFormUI() {
        /* Abre arquivo com dados da árvore */
        CarregarArquivo();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Árvore Genealógica");

        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Data de Nascimento");

        jLabel3.setText("Cônjuge");

        jLabel4.setText("Profissão");

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Informações");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ver árvore");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Pai/Mãe");

        jLabel7.setText("Cidade");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Selecionar Árvore");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jTextField1)
                        .addComponent(jTextField3)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(GetPath() != null){
            LocalDate nasc_raiz = LocalDateTime.ofInstant(GetArvore().GetRaiz().GetDataNascimento().toInstant(), ZoneOffset.UTC).toLocalDate();
            LocalDate data_atual = LocalDate.now();
            Period periodo = Period.between(nasc_raiz, data_atual);
            int dias = periodo.getDays();
            int meses = periodo.getMonths();
            int anos = periodo.getYears();
            JFrame frame = new JFrame("Buscar na Árvore");
            Nodo raiz = null;

            JOptionPane.showMessageDialog(frame,
                        "Raiz: \n" + GetArvore().GetRaiz().GetNome() + "\n"
                        + "\nQuanto tempo desde nascimento da raiz: \n" + dias + " dias, " + meses + " meses e " + anos+ " anos."+"\n"
                        + "\nQuantidade de gerações da família: \n" + GetArvore().GetGeracoes(), //mensagem
                "Informações da árvore", // titulo da janela 
                JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Você não selecionou nenhuma árvore.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:     
        //   InserirNodo(nome_pai, nome, cidade, profissao, conjuge, data_nasc, filho)
//        System.out.println(jTextField6.getText());
//        System.out.println(jTextField7.getText());
        if(!"".equals(jTextField7.getText())
                && !"".equals(jTextField6.getText()) && !"".equals(jTextField1.getText()) && !"".equals(jTextField4.getText())
                && !"".equals(jTextField3.getText()) && !"".equals(jTextField3.getText())
                && !"".equals(jTextField2.getText())){
            try {
                if(GetArvore().GetRaiz() == null){
                    GetArvore().InserirNodo("Jesus", jTextField1.getText(), jTextField7.getText(), jTextField4.getText(), jTextField3.getText(), data_nasc.parse(jTextField2.getText()), null);
                }else{
                    GetArvore().InserirNodo(jTextField6.getText(), jTextField1.getText(), jTextField7.getText(), jTextField4.getText(), jTextField3.getText(), data_nasc.parse(jTextField2.getText()), null);
                }
                try {// Escreve no documento 'arvore.txt' o novo nodo inserido.
                    BufferedWriter bw = new BufferedWriter(new FileWriter(GetPath(), true));
                    bw.append("\n"+jTextField6.getText()+","+jTextField1.getText()+","+jTextField7.getText()+","+jTextField4.getText()+","+jTextField3.getText()+","+jTextField2.getText()+";");
                    bw.close();
                } catch (IOException ex) {
                    Logger.getLogger(ArvoreFormUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                JFrame frame = new JFrame("Inserir na Árvore");
                // Cria o JOptionPane por showMessageDialog
                JOptionPane.showMessageDialog(frame,
                    "Inserido na árvore com sucesso!", //mensagem
                    "Árvore", // titulo da janela 
                    JOptionPane.INFORMATION_MESSAGE);

            } catch (ParseException ex) {
                    Logger.getLogger(ArvoreFormUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Todos os campos devem estar preenchidos.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(GetPath() != null){
            SetGrafo(new Grafos());
            GetGrafo().AddGrafo(GetArvore(), GetGrafo());
            GetGrafo().RoamingMouseEvent(GetArvore()); // Chama a função para rondar os cliques assim que o grafo com a árvore é iniciado.
        }else{
            JOptionPane.showMessageDialog(null, "Você não selecionou nenhuma árvore.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        // Cria um JFrame
        JFrame frame = new JFrame("Buscar na Árvore");
        // Cria o JOptionPane por showMessageDialog
        String procurado = JOptionPane.showInputDialog("Informe o Nome/Cidade do filho :");
        if(procurado != null){
            Nodo achado = GetArvore().Buscar(procurado, GetArvore().GetRaiz());
            if(achado != null){
                String nome_pai;
                if(achado.GetPai() == null){
                    nome_pai = "Jesus";
                }else{
                    nome_pai = achado.GetPai().GetNome();
                }
                JOptionPane.showMessageDialog(frame,
                            "Pai: \n" + nome_pai + "\n"
                            + "\nNome: \n" + achado.GetNome() + "\n"
                            + "\nData Nascimento: \n" + achado.GetDataNascimento().toString() + "\n"
                            + "\nCônjuge: \n" + achado.GetConjuge() + "\n"
                            + "\nProfissão: \n" + achado.GetProfissao() + "\n"
                            + "\nCidade: \n" + achado.GetCidade() + "\n"
                            + "\nFilhos: \n" + achado.GetListaFilhos().GetFilhos(achado.GetListaFilhos().GetUltimoFilho()), //mensagem
                    "Informações da pessoa procurada", // titulo da janela 
                    JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(frame, "Error: pessoa não encontrada!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
                // restringe a amostra a diretorios apenas
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res = fc.showOpenDialog(null);
        if(res == JFileChooser.APPROVE_OPTION){
            File diretorio = fc.getSelectedFile();
            String path_dir = diretorio.getAbsolutePath();
            path_dir = path_dir + "\\arvore.txt";
            JOptionPane.showMessageDialog(null, "Voce escolheu o diretório: " + path_dir);
            SetPath(path_dir);
            CarregarArquivo();
        }
        else
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum diretorio.");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArvoreFormUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArvoreFormUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArvoreFormUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArvoreFormUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArvoreFormUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
